### ISSUE TITLE
Permission check failure

### ISSUE THREAD

**Issue by ghost** [KelvinTegelaar/CyberDrain#1]
Hello, I am new to CIPP and have been trying to set it up following the guide.

Error when running check: We could not connect to the API to retrieve the permissions. There might be a problem with the secure application model configuration. The returned error is: invalid_grant:AADSTS9002313: Invalid request. Request is malformed or invalid.

Any ideas? I have restarted the function app. It looks like permissions issue so probably something simple?

Thank you

**Comment by KelvinTegelaar** [comment]
issues are not for support, only sponsors get support.

**Comment by ghost** [comment]
Thanks Kelvin - how do I get support I have sponsored

**Comment by KelvinTegelaar** [comment]
Sponsors at the right level automatically receive an email with details.

**Comment by ghost** [comment]
Thank you. I have signed up for the $15 originally then changed to $99. I have not yet received an email I will keep waiting.

Cheers
